<a href="https://colab.research.google.com/github/minkyeongk/MachineLearning_Basic/blob/master/Lab4_Iris_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
# import library
import tensorflow as tf
import pandas as pd

In [13]:
# 1. prepare last data 
file_path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris = pd.read_csv(file_path)
iris.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [20]:
# onehot-encoding
onehot = pd.get_dummies(iris)
onehot.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [21]:
print(onehot.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [22]:
# separate independent and dependent variables
independent = onehot[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
dependent = onehot[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(independent.shape, dependent.shape)

(150, 4) (150, 3)


In [23]:
# 2. create structure of model
x = tf.keras.layers.Input(shape=[4])
y = tf.keras.layers.Dense(3, activation='softmax')(x)
model = tf.keras.models.Model(x, y)
model.compile(loss = 'categorical_crossentropy', metrics = 'accuracy')

In [26]:
# 3. train model
model.fit(independent, dependent, epochs = 1000, verbose = 0)
model.fit(independent, dependent, epochs = 10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0960 - accuracy: 0.9800
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0958 - accuracy: 0.9733
Epoch 3/10
5/5 [==============================] - 0s 1ms/step - loss: 0.0959 - accuracy: 0.9800
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0960 - accuracy: 0.9800
Epoch 5/10
5/5 [==============================] - 0s 1ms/step - loss: 0.0958 - accuracy: 0.9800
Epoch 6/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0957 - accuracy: 0.9800
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0957 - accuracy: 0.9800
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0955 - accuracy: 0.9800
Epoch 9/10
5/5 [==============================] - 0s 1ms/step - loss: 0.0958 - accuracy: 0.9800
Epoch 10/10
5/5 [==============================] - 0s 1ms/step - loss: 0.0956 - accuracy: 0.9800


In [27]:
# 4. use the model
model.predict(independent[0:5])

array([[9.9996912e-01, 3.0824882e-05, 4.5447751e-12],
       [9.9971324e-01, 2.8674252e-04, 1.7504612e-10],
       [9.9992144e-01, 7.8512501e-05, 3.2170062e-11],
       [9.9967074e-01, 3.2924998e-04, 3.1553962e-10],
       [9.9997950e-01, 2.0555151e-05, 2.7980296e-12]], dtype=float32)

In [28]:
print(dependent[0:5])

   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [30]:
model.predict(independent[-5:])

array([[6.9910228e-10, 4.1259538e-02, 9.5874047e-01],
       [1.9738509e-09, 9.2359200e-02, 9.0764081e-01],
       [6.8528814e-09, 1.3398868e-01, 8.6601132e-01],
       [9.7038033e-10, 3.0762011e-02, 9.6923792e-01],
       [2.8648801e-08, 1.8921381e-01, 8.1078619e-01]], dtype=float32)

In [31]:
print(dependent[-5:])

     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [32]:
# print weight and bias
model.get_weights()

[array([[ 1.1493667 ,  0.85734904, -0.6020033 ],
        [ 4.6281486 ,  0.28392112, -1.9739555 ],
        [-5.3404217 , -0.48949653,  1.9003339 ],
        [-6.294764  , -2.4175696 ,  2.8206506 ]], dtype=float32),
 array([ 3.2591066,  1.9993021, -2.7786937], dtype=float32)]

In [ ]:
# 위 결과의 열은 각 붓꽃 종류를 예측하는 가중치라는 것 > 하나의 수식 
# 위에서부터 차례대로 각 독립변수에 곱해지는 값
# 마지막 배열은 bias 