<a href="https://colab.research.google.com/github/minkyeongk/MachineLearning_Basic/blob/master/Lab5_2_Hidden_Layer(Iris).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# import library
import tensorflow as tf
import pandas as pd

In [4]:
# 1. prepare last data 
file_path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris = pd.read_csv(file_path)
iris.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [5]:
# onehot-encoding
onehot = pd.get_dummies(iris)
onehot.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [6]:
print(onehot.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [7]:
# separate independent and dependent variables
independent = onehot[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
dependent = onehot[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(independent.shape, dependent.shape)

(150, 4) (150, 3)


In [8]:
# 2. create structure of model
x = tf.keras.layers.Input(shape=[4])

# add 3 hidden layers
h = tf.keras.layers.Dense(8, activation='swish')(x)
h = tf.keras.layers.Dense(8, activation='swish')(h)
h = tf.keras.layers.Dense(8, activation='swish')(h)
y = tf.keras.layers.Dense(3, activation='softmax')(h)
model = tf.keras.models.Model(x, y)
model.compile(loss = 'categorical_crossentropy', metrics = 'accuracy')

In [9]:
# 3. train model
model.fit(independent, dependent, epochs = 1000, verbose = 0)
model.fit(independent, dependent, epochs = 10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0504 - accuracy: 0.9800
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0487 - accuracy: 0.9733
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0421 - accuracy: 0.9800
Epoch 4/10
5/5 [==============================] - 0s 1ms/step - loss: 0.0490 - accuracy: 0.9800
Epoch 5/10
5/5 [==============================] - 0s 1ms/step - loss: 0.0520 - accuracy: 0.9733
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0441 - accuracy: 0.9800
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0491 - accuracy: 0.9800
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0542 - accuracy: 0.9800
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0478 - accuracy: 0.9867
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0424 - accuracy: 0.9867


In [10]:
# 4. use the model
model.predict(independent[0:5])

array([[1.0000000e+00, 7.8725187e-10, 7.1628610e-09],
       [1.0000000e+00, 3.2092412e-08, 2.0962064e-08],
       [1.0000000e+00, 6.3734666e-09, 1.3780650e-08],
       [9.9999988e-01, 9.1413163e-08, 2.1867136e-08],
       [1.0000000e+00, 5.3147764e-10, 6.4513874e-09]], dtype=float32)

In [11]:
print(dependent[0:5])

   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [12]:
model.predict(independent[-5:])

array([[8.4018981e-10, 4.2248168e-04, 9.9957746e-01],
       [4.7496234e-09, 7.7832825e-03, 9.9221671e-01],
       [3.0345726e-09, 5.7984428e-03, 9.9420148e-01],
       [2.6837621e-10, 1.0287075e-04, 9.9989712e-01],
       [9.8172883e-09, 2.3421764e-02, 9.7657824e-01]], dtype=float32)

In [13]:
print(dependent[-5:])

     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [14]:
# print weight and bias
model.get_weights()

[array([[-0.39759094, -0.38698715, -0.28744233,  0.13336241, -0.6615622 ,
         -0.1446563 , -0.01473106,  0.24997808],
        [ 0.51929206,  0.02859916, -0.54125804,  0.51079047,  0.03282497,
          0.6764843 , -0.4777213 ,  0.48601443],
        [-0.45551065,  0.42408305,  0.35423923, -0.23221536,  0.49942917,
          0.5212882 ,  0.41130435, -0.84198123],
        [-0.05978721,  0.46736032, -0.6061281 , -0.02459325, -0.62474   ,
         -0.0057015 ,  0.6050715 , -0.9491643 ]], dtype=float32),
 array([ 0.28114042,  0.20595138,  0.12366533,  0.22530371, -0.07636168,
         0.03910398, -0.05922315,  0.28771406], dtype=float32),
 array([[-0.3659009 , -0.19897926, -0.33311167, -0.50321823,  0.240287  ,
          0.3136698 ,  0.30864757, -0.22621669],
        [-0.7845782 , -1.0682536 , -0.6570886 , -0.21763584,  0.34137067,
         -0.34053499,  0.25353235, -0.10611072],
        [-0.82528853, -0.8382195 , -0.88784754, -0.23434852, -0.14577816,
         -0.68440735,  0.25304958,

In [ ]:
# 위 결과의 열은 각 붓꽃 종류를 예측하는 가중치라는 것 > 하나의 수식 
# 위에서부터 차례대로 각 독립변수에 곱해지는 값
# 마지막 배열은 bias 